version: '3.5'
services:
  front:
    build:
      context: './'
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    container_name: next-app-container
    networks:
      - mern-stack-network
    volumes:
      - ./:/app
      - /app/node_modules 
networks:
  mern-stack-network:
